apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dvn-workshop
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/andreinfracloud/projetodevopsnanuvem-gitops.git
    targetRevision: HEAD
    path: dvn-workshop-kubernetes/argocd/.
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true