
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend/deploy.yml
- frontend/service.yml
- backend/deploy.yml
- backend/service.yml
- ingress.yml
- argocd/application.yml
  

images:
- name: 835928001161.dkr.ecr.us-east-1.amazonaws.com/dvn-workshop/production/backend
  newName: 835928001161.dkr.ecr.us-east-1.amazonaws.com/dvn-workshop/production/backend
  newTag: 81c087db2841537cac4b51238b930fb328aa96ec
- name: 835928001161.dkr.ecr.us-east-1.amazonaws.com/dvn-workshop/production/frontend
  newName: 835928001161.dkr.ecr.us-east-1.amazonaws.com/dvn-workshop/production/frontend
  newTag: 81c087db2841537cac4b51238b930fb328aa96ec
