
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend/deploy.yml
- frontend/service.yml
- backend/deploy.yml
- backend/service.yml
- ingress.yml
- argocd/application.yml
  

images:
- name: 835928001161.dkr.ecr.us-east-1.amazonaws.com/dvn-workshop/production/backend
  newName: 835928001161.dkr.ecr.us-east-1.amazonaws.com/dvn-workshop/production/backend
  newTag: 744143e0d7a0790152ddcee474e3c4195c3bc826
- name: 835928001161.dkr.ecr.us-east-1.amazonaws.com/dvn-workshop/production/frontend
  newName: 835928001161.dkr.ecr.us-east-1.amazonaws.com/dvn-workshop/production/frontend
  newTag: 53e0088170143926eb0a15a0005e66e45126472b
